### ISSUE TITLE
Does not work on .rar

### ISSUE THREAD

**Issue by timothevs** [pashifika/comic-auto-resize#2]
No matter what rar file I may try

[FATAL] unknown encoder

This is on macOS 12.2 using the latest 1.1.0

Using debug I see that the rar file is decoded, and the images are all processed. It even creates a 0 byte size file _resize.rar, but fails at the last step.

```bash
[DEBUG] path: B128.jpg  resize to: width=1440 height=2177
[DEBUG] path: B129.jpg  resize to: width=1440 height=2176
[FATAL] unknown encoder
```

**Comment by pashifika** [comment]
please try the ratio option.

**Comment by timothevs** [comment]
Not sure if it is ratio related.

I renamed the .cbr and changed the file extension to .zip. Tried it with the tool, and it converted it just fine. It will not work for some reason with .rar or .cbr

Additionally if the files inside the archive have any special characters like &, and ., the conversion fails immediately.

**Comment by pashifika** [comment]
please try the out option,
`-o, --out:                     set output file path (default is add suffix '_resize' to file name).`
and set the file extension to the correct ZIP.

**Comment by timothevs** [comment]
Yep this works `./comic-auto-resize --out=abc.zip Draupadi.cbr` , but it doesn't when you try `--out=abc.cbz`

**Comment by pashifika** [comment]
`compressor.CreateArchiverFile` is check to output file name extension.
