### ISSUE TITLE
Periods, and special chars in filename will cause "too many open files" error

### ISSUE THREAD

**Issue by timothevs** [pashifika/comic-auto-resize#3]
The zip in question has files with periods in its name. Conversion fails immediately with the error

`[FATAL] open /Volumes/Scratch/Utils/COMIX/Bronze Age (2018).cbz: too many open files`

**Comment by pashifika** [comment]
see https://pkg.go.dev/io/fs#WalkDir `.` and other special characters directory names are not supported.
